# Generated by Django 5.2.18 on 2026-10-08 05:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('succeeded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('committee', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_elapsed', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100)])),
                ('risk_elapsed', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)])),
                ('risk_progress', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100)])),
                ('stale_days', models.PositiveSmallIntegerField(default=5)),
                ('remind_days', models.PositiveSmallIntegerField(default=3)),
                ('head_after', models.PositiveSmallIntegerField(default=1)),
                ('assistant_after', models.PositiveSmallIntegerField(default=3)),
                ('executive_after', models.PositiveSmallIntegerField(default=7)),
                ('critical_multiplier', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'مسؤول النظام'), ('executive', 'المدير التنفيذي'), ('assistant', 'مساعد المدير التنفيذي'), ('head', 'رئيس الوحدة'), ('employee', 'موظف'), ('viewer', 'عرض فقط')], default='employee', max_length=20)),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, unique=True)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('followup_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('decision', 'قرار اجتماع'), ('executive', 'تكليف المدير التنفيذي'), ('plan', 'خطة تشغيلية'), ('inbound', 'مراسلة واردة'), ('outbound', 'مراسلة صادرة'), ('internal', 'إجراء داخلي'), ('project', 'مشروع'), ('unit', 'طلب وحدة'), ('independent', 'مهمة مستقلة'), ('other', 'أخرى')], default='independent', max_length=20)),
                ('task_type', models.CharField(default='تشغيلية', max_length=100)),
                ('project', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(db_index=True)),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('important', 'مهمة'), ('urgent', 'عاجلة'), ('critical', 'حرجة')], db_index=True, default='normal', max_length=20)),
                ('confidentiality', models.CharField(choices=[('normal', 'عادية'), ('restricted', 'مقيدة'), ('secret', 'سرية')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('assigned', 'تم الإسناد'), ('active', 'قيد التنفيذ'), ('waiting', 'بانتظار رد'), ('external', 'بانتظار جهة خارجية'), ('blocked', 'متعثرة'), ('overdue', 'متأخرة'), ('completed', 'مكتملة'), ('approval', 'بانتظار الاعتماد'), ('returned', 'معادة للتنفيذ'), ('paused', 'موقوفة'), ('cancelled', 'ملغاة'), ('closed', 'مغلقة')], db_index=True, default='assigned', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_progress', models.BooleanField(default=False)),
                ('expected_result', models.TextField()),
                ('success_indicator', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.decision')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('due_date', models.DateField()),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('انتظار اعتماد', 'انتظار اعتماد'), ('نقص معلومات', 'نقص معلومات'), ('نقص موارد', 'نقص موارد'), ('نقص موظفين', 'نقص موظفين'), ('اعتماد مالي', 'اعتماد مالي'), ('اعتماد إداري', 'اعتماد إداري'), ('جهة خارجية', 'جهة خارجية'), ('مشكلة تقنية', 'مشكلة تقنية'), ('ضغط أعمال', 'ضغط أعمال'), ('تأخر مورد', 'تأخر مورد'), ('تأخر وحدة أخرى', 'تأخر وحدة أخرى'), ('أخرى', 'أخرى')], max_length=100)),
                ('description', models.TextField()),
                ('caused_by', models.CharField(max_length=200)),
                ('needs_decision', models.BooleanField(default=False)),
                ('requested_action', models.TextField()),
                ('expected_resolution', models.DateField()),
                ('impact', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('intervention_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_obstacles', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_obstacles', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obstacles', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('level', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('old', models.JSONField(default=dict)),
                ('new', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.task')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.comment')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.decision')),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.subtask')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='participating_units',
            field=models.ManyToManyField(blank=True, related_name='shared_tasks', to='core.unit'),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.unit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_units',
            field=models.ManyToManyField(blank=True, to='core.unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.unit'),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField()),
                ('accomplished', models.TextField()),
                ('remaining', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='subtask_progress_max'),
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.UniqueConstraint(fields=('task', 'recipient', 'level'), name='unique_escalation'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['unit', 'status'], name='core_task_unit_id_6ef512_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status'], name='core_task_owner_i_ca7b32_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='task_progress_max'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date'))), name='task_dates_order'),
        ),
    ]
