# Generated by Django 5.2.18 on 2026-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_mode',
            field=models.CharField(choices=[('manual', 'موظف أو موظفون محددون'), ('unit', 'جميع موظفي الوحدة القائدة'), ('units', 'موظفو الوحدة القائدة والوحدات المشاركة')], default='manual', max_length=20),
        ),
    ]
