# Generated by Django 5.2.18 on 2026-10-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_assignment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'حالات المهام'), ('priority', 'الأولويات'), ('task_type', 'أنواع المهام')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='unique_catalog_entry')],
            },
        ),
    ]
