# Generated by Django 5.2.18 on 2026-10-08 06:13

from django.db import migrations, models


LIFECYCLE={'new','assigned','active','waiting','external','completed','approval','returned','paused','cancelled','closed'}

def restore_lifecycle(apps,schema_editor):
    Task=apps.get_model('core','Task'); Audit=apps.get_model('core','Audit'); Catalog=apps.get_model('core','Catalog')
    db=schema_editor.connection.alias
    for task in Task.objects.using(db).filter(status__in=['overdue','blocked']).iterator():
        recovered=None
        for event in Audit.objects.using(db).filter(task_id=task.pk).order_by('-created_at','-pk').iterator():
            for snapshot in [event.new,event.old]:
                candidate=snapshot.get('status')
                if candidate in LIFECYCLE:
                    recovered=candidate; break
            if recovered: break
        source='audit' if recovered else 'fallback'
        recovered=recovered or ('approval' if task.progress==100 else 'active' if task.progress else 'assigned')
        Task.objects.using(db).filter(pk=task.pk).update(status=recovered)
        Audit.objects.using(db).create(task_id=task.pk,actor_id=None,action='فصل مؤشرات التأخر والتعثر عن الحالة',old={'status':task.status},new={'status':recovered,'recovery':source})
    Catalog.objects.using(db).filter(kind='status',key__in=['overdue','blocked']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_catalog'),
    ]

    operations = [
        migrations.RunPython(restore_lifecycle,migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('assigned', 'تم الإسناد'), ('active', 'قيد التنفيذ'), ('waiting', 'بانتظار رد'), ('external', 'بانتظار جهة خارجية'), ('completed', 'مكتملة'), ('approval', 'بانتظار الاعتماد'), ('returned', 'معادة للتنفيذ'), ('paused', 'موقوفة'), ('cancelled', 'ملغاة'), ('closed', 'مغلقة')], db_index=True, default='assigned', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'assigned', 'active', 'waiting', 'external', 'completed', 'approval', 'returned', 'paused', 'cancelled', 'closed'])), name='task_lifecycle_status'),
        ),
    ]
