# Generated by Django 5.2.18 on 2026-10-08 06:26

import django.db.models.deletion
from django.db import migrations, models
from importlib import import_module

immutable=import_module('core.migrations.0002_audit_immutable')


def preserve_legacy_decision_audits(apps,schema_editor):
    Audit=apps.get_model('core','Audit'); Decision=apps.get_model('core','Decision'); db=schema_editor.connection.alias
    for event in Audit.objects.using(db).filter(task__isnull=True,decision__isnull=True,action__in=['حفظ قرار','حفظ قرار اجتماع','رفع مرفق قرار']).order_by('created_at','pk').iterator():
        decision_id=event.new.get('decision') or event.new.get('id')
        if not str(decision_id).isdigit() or not Decision.objects.using(db).filter(pk=decision_id).exists(): continue
        Audit.objects.using(db).create(decision_id=decision_id,actor_id=event.actor_id,action='سجل سابق: '+event.action,old=event.old,new={**event.new,'original_audit_id':event.pk,'original_created_at':event.created_at.isoformat(),'reason':event.new.get('reason') or event.new.get('comment') or 'لم يسجّل سبب في الإصدار السابق'})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_indicators'),
    ]

    operations = [
        migrations.RunPython(immutable.uninstall,immutable.install),
        migrations.AddField(
            model_name='audit',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.decision'),
        ),
        migrations.AddField(
            model_name='decision',
            name='approved_minutes_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_decisions', to='core.attachment'),
        ),
        migrations.AddField(
            model_name='decision',
            name='approved_minutes_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='issuing_authority',
            field=models.CharField(blank=True, choices=[('board', 'مجلس الإدارة'), ('assembly', 'الجمعية العمومية'), ('committee', 'لجنة')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='decision',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('active', 'قيد التنفيذ'), ('executed', 'منفّذ'), ('amended', 'معدّل'), ('cancelled', 'ملغى')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'active', 'executed', 'amended', 'cancelled'])), name='decision_lifecycle_status'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('date')), _connector='OR'), name='decision_dates_order'),
        ),
        migrations.RunPython(immutable.install,immutable.uninstall),
        migrations.RunPython(preserve_legacy_decision_audits,migrations.RunPython.noop),
    ]
