# Generated by Django 5.2.18 on 2026-10-08 06:41

from django.db import migrations, models


def reconcile_progress(apps,schema_editor):
    Task=apps.get_model('core','Task'); Audit=apps.get_model('core','Audit'); Decision=apps.get_model('core','Decision'); Obstacle=apps.get_model('core','Obstacle')
    db=schema_editor.connection.alias; decisions={}
    def metrics(decision_id):
        values=list(Task.objects.using(db).filter(decision_id=decision_id).values_list('progress','status'))
        return {'progress':round(sum(p for p,s in values)/len(values)) if values else 0,'approved_progress':round(sum(s=='closed' for p,s in values)/len(values)*100) if values else 0}
    for task in Task.objects.using(db).all().iterator():
        changes={}
        if task.status in ['approval','completed','closed'] and task.progress<100:
            changes={'status':'returned' if task.status=='closed' else 'active' if task.progress else 'assigned','submitted_at':None,'closed_at':None}
        elif task.progress==100 and task.status not in ['approval','completed','closed','cancelled']:
            if Obstacle.objects.using(db).filter(task_id=task.pk,resolved_at__isnull=True).exists():
                changes={'status':'returned','progress':99,'submitted_at':None,'closed_at':None}
            else: changes={'status':'approval'}
        if not changes: continue
        if task.decision_id and task.decision_id not in decisions: decisions[task.decision_id]=metrics(task.decision_id)
        old={'status':task.status,'progress':task.progress,'submitted_at':str(task.submitted_at) if task.submitted_at else None,'closed_at':str(task.closed_at) if task.closed_at else None}
        Task.objects.using(db).filter(pk=task.pk).update(**changes)
        Audit.objects.using(db).create(task_id=task.pk,action='تصحيح تعارض الحالة ونسبة الإنجاز',old=old,new={**old,**changes,'reason':'ترحيل ضبط الاتساق؛ لم تُرفع نسبة إنجاز ناقصة، وأعيدت نسبة 100% ذات العائق إلى التنفيذ عند 99%.'})
    for decision_id,before in decisions.items():
        Audit.objects.using(db).create(decision_id=decision_id,action='تصحيح نسب القرار بعد ضبط الاتساق',old=before,new={**metrics(decision_id),'derived':True,'reason':'ترحيل ضبط اتساق المهام المرتبطة.'})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_decision_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacle',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مسؤول النظام'), ('executive', 'المدير التنفيذي'), ('assistant', 'مساعد المدير التنفيذي'), ('head', 'رئيس الوحدة'), ('employee', 'موظف'), ('viewer', 'عرض فقط'), ('board', 'مجلس الإدارة / أمين المجلس')], default='employee', max_length=20),
        ),
        migrations.RunPython(reconcile_progress,migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('progress', 100), ('status__in', ['approval', 'completed', 'closed'])), ('status', 'cancelled'), models.Q(models.Q(('status__in', ['approval', 'completed', 'closed', 'cancelled']), _negated=True), ('progress__lt', 100)), _connector='OR'), name='task_status_progress_consistent'),
        ),
    ]
