# Generated by Django 5.2.18 on 2026-10-08 13:33

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_board_followup_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('board', 'مجلس الإدارة'), ('assembly', 'الجمعية العمومية'), ('committee', 'لجنة')], max_length=20)),
                ('mandate', models.TextField()),
                ('starts', models.DateField()),
                ('ends', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='meetinghub.auditstream')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'رئيس المجلس'), ('secretary', 'أمين السر'), ('member', 'عضو'), ('observer', 'مراقب')], default='member', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('capacity', models.CharField(blank=True, max_length=150)),
                ('starts', models.DateField()),
                ('ends', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('identity_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('identity_encrypted', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ordinary', 'عادي'), ('extraordinary', 'غير عادي'), ('emergency', 'طارئ')], max_length=20)),
                ('mode', models.CharField(choices=[('onsite', 'حضوري'), ('remote', 'عن بعد'), ('hybrid', 'هجين')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('connection_url', models.URLField(blank=True)),
                ('rsvp_deadline', models.DateTimeField()),
                ('quorum_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01")), django.core.validators.MaxValueValidator(100)])),
                ('quorum_reference', models.CharField(max_length=250)),
                ('allow_proxy', models.BooleanField(default=False)),
                ('proxy_limit', models.PositiveSmallIntegerField(default=0)),
                ('secrecy', models.CharField(choices=[('internal', 'داخلي'), ('secret', 'سري')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدول'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=20)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetinghub.committee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='governance', to='core.meeting')),
                ('invitees', models.ManyToManyField(related_name='meetings', to='meetinghub.member')),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaired_committees', to='meetinghub.member'),
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(related_name='committees', to='meetinghub.member'),
        ),
        migrations.AddField(
            model_name='committee',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretary_committees', to='meetinghub.member'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gte', models.F('starts')), _connector='OR'), name='meeting_member_period'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['chair', 'secretary', 'member', 'observer'])), name='meeting_member_role'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='meeting_time_order'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('rsvp_deadline__lte', models.F('starts_at'))), name='meeting_rsvp_order'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quorum_percent__gt', 0), ('quorum_percent__lte', 100)), name='meeting_quorum_range'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'scheduled', 'cancelled'])), name='meeting_hub_status'),
        ),
        migrations.AddConstraint(
            model_name='committee',
            constraint=models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gte', models.F('starts')), _connector='OR'), name='meeting_committee_period'),
        ),
    ]
