# Generated by Django 5.2.18 on 2026-10-08 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_followup_integrity'),
        ('meetinghub', '0002_immutable_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='agenda_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='final_reminder_hours',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='meeting_reminder_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='roster_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('briefing', 'إحاطة'), ('discussion', 'نقاش'), ('decision', 'قرار'), ('vote', 'تصويت'), ('minutes', 'اعتماد محضر'), ('secret', 'سري'), ('information', 'معلومات')], max_length=20)),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('removed', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_items', to='meetinghub.meetingrecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='meetinghub.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='meetinghub.agendaitem')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='meetinghub.member')),
                ('previous_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.decision')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AgendaRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('items', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_revisions', to='meetinghub.meetingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=20)),
                ('invited', models.BooleanField()),
                ('quorum_eligible', models.BooleanField()),
                ('voting_eligible', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetinghub.member')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('remote', 'حاضر عن بعد'), ('left', 'غادر'), ('disconnected', 'فقد الاتصال'), ('absent', 'متغيب')], default='absent', max_length=20)),
                ('first_entered_at', models.DateTimeField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('verification', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('eligibility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='meetinghub.eligibility')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(choices=[('pending', 'لم يرد'), ('confirm', 'أكد الحضور'), ('decline', 'اعتذر'), ('proxy', 'طلب حضور بالتوكيل')], default='pending', max_length=15)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invitation', to='meetinghub.eligibility')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('agenda', 'جدول الأعمال'), ('proxy', 'وثيقة توكيل')], default='agenda', max_length=10)),
                ('protected', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='meeting-files/%Y/%m/')),
                ('name', models.CharField(max_length=250)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='meetinghub.agendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='meetinghub.meetingrecord')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadAcknowledgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetinghub.member')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgments', to='meetinghub.agendarevision')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('midpoint', 'منتصف مهلة التأكيد'), ('final', 'قبل نهاية المهلة'), ('meeting', 'قبل الاجتماع')], max_length=20)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='meetinghub.invitation')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('quorum_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quorum_reference', models.CharField(max_length=250)),
                ('eligible_count', models.PositiveIntegerField()),
                ('required', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters', to='meetinghub.meetingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField()),
                ('attendance_allowed', models.BooleanField(default=False)),
                ('voting_allowed', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_proxies', to='meetinghub.eligibility')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxy_records', to='meetinghub.meetingfile')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_proxies', to='meetinghub.eligibility')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxies', to='meetinghub.roster')),
            ],
        ),
        migrations.AddField(
            model_name='eligibility',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='meetinghub.roster'),
        ),
        migrations.AddConstraint(
            model_name='agendarevision',
            constraint=models.UniqueConstraint(fields=('meeting', 'version'), name='meeting_agenda_version'),
        ),
        migrations.AddConstraint(
            model_name='readacknowledgment',
            constraint=models.UniqueConstraint(fields=('revision', 'member'), name='meeting_agenda_read_once'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('invitation', 'kind'), name='meeting_reminder_dedup'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('meeting', 'generation'), name='meeting_roster_generation'),
        ),
        migrations.AddConstraint(
            model_name='proxy',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('roster', 'principal'), name='meeting_one_live_proxy'),
        ),
        migrations.AddConstraint(
            model_name='proxy',
            constraint=models.CheckConstraint(condition=models.Q(('principal', models.F('delegate')), _negated=True), name='meeting_proxy_distinct'),
        ),
        migrations.AddConstraint(
            model_name='eligibility',
            constraint=models.UniqueConstraint(fields=('roster', 'member'), name='meeting_roster_member'),
        ),
    ]
