# Generated by Django 5.2.18 on 2026-10-08 07:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_board_followup_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('IN', 'وارد خارجي'), ('OUT', 'صادر خارجي'), ('INT', 'مذكرة داخلية'), ('CIR', 'تعميم'), ('DEC', 'قرار إداري'), ('RPL', 'رد على وارد')], max_length=4)),
                ('levels', models.JSONField(default=list, help_text='قائمة مرتبة للأدوار: head, assistant, executive')),
                ('authority_reference', models.CharField(help_text='مرجع مصفوفة الصلاحيات المعتمدة', max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_days', models.JSONField(default=dict, help_text='normal/important/urgent/critical: أيام عمل')),
                ('referral_hours', models.JSONField(default=dict)),
                ('weekend', models.JSONField(default=list, help_text='أرقام أيام الأسبوع: الاثنين 0؛ الجمعة 4 والسبت 5')),
                ('work_start', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(23)])),
                ('work_end', models.PositiveSmallIntegerField(default=17, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('reminder_percent', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('manager_percent', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)])),
                ('executive_percent', models.PositiveSmallIntegerField(default=150, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500)])),
                ('source_system', models.CharField(default='Snso — الربط غير مفعّل', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('supervisory', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('legal_reference', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='correspondence.classification')),
                ('route_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
                ('retention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.retentionpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('kind', models.CharField(choices=[('IN', 'وارد خارجي'), ('OUT', 'صادر خارجي'), ('INT', 'مذكرة داخلية'), ('CIR', 'تعميم'), ('DEC', 'قرار إداري'), ('RPL', 'رد على وارد')], max_length=4)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('external_number', models.CharField(blank=True, max_length=100)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('secrecy', models.CharField(choices=[('public', 'عام'), ('internal', 'داخلي'), ('restricted', 'مقيّد'), ('secret', 'سري')], default='internal', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'عادية'), ('important', 'مهمة'), ('urgent', 'عاجلة'), ('critical', 'حرجة')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('registered', 'مسجّل'), ('referred', 'محال'), ('active', 'قيد المعالجة'), ('waiting', 'بانتظار رد جهة خارجية'), ('review', 'تدقيق'), ('approval', 'بانتظار اعتماد'), ('signing', 'بانتظار توقيع'), ('issued', 'مُصدَر برقم'), ('sent', 'مُرسَل'), ('received', 'مستلم'), ('done', 'منجز'), ('archived', 'مؤرشف'), ('returned', 'مُعاد للتصحيح'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=20)),
                ('channel', models.CharField(choices=[('manual', 'يدوي'), ('email', 'بريد مؤسسي'), ('portal', 'بوابة'), ('api', 'API'), ('platform', 'منصة حكومية')], default='manual', max_length=20)),
                ('source_platform', models.CharField(blank=True, max_length=150)),
                ('no_attachments', models.BooleanField(default=False)),
                ('approval_roles', models.JSONField(default=list)),
                ('approval_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('referral_due_at', models.DateTimeField(blank=True, null=True)),
                ('external_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_hours', models.FloatField(default=80)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('signature_method', models.CharField(blank=True, max_length=20)),
                ('signature_evidence', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_evidence', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('retain_until', models.DateField(blank=True, null=True)),
                ('legacy_reference', models.CharField(blank=True, max_length=100)),
                ('authorized', models.ManyToManyField(blank=True, related_name='authorized_mail', to=settings.AUTH_USER_MODEL)),
                ('cc', models.ManyToManyField(blank=True, related_name='cc_mail', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.classification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mail', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondence', to='core.decision')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_mail', to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='correspondence.correspondence')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='correspondence.approvalroute')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_mail', to=settings.AUTH_USER_MODEL)),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signable_mail', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('reason', models.TextField()),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_delegated_to', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_delegations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.BooleanField(default=False)),
                ('templates', models.BooleanField(default=False)),
                ('compliance', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mail_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='correspondence.correspondence')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='correspondence/%Y/%m/')),
                ('name', models.CharField(max_length=250)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='correspondence.correspondence')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('old', models.JSONField(default=dict)),
                ('new', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='correspondence.correspondence')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('IN', 'وارد خارجي'), ('OUT', 'صادر خارجي'), ('INT', 'مذكرة داخلية'), ('CIR', 'تعميم'), ('DEC', 'قرار إداري'), ('RPL', 'رد على وارد')], max_length=4)),
                ('body', models.TextField(help_text='متغيرات معتمدة بصيغة {{الموضوع}}؛ لا يقبل كودًا أو HTML.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='mail_template_version')],
            },
        ),
        migrations.AddField(
            model_name='correspondence',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='correspondence.mailtemplate'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.party'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(choices=[('view', 'للاطلاع'), ('reply', 'للإفادة'), ('study', 'للدراسة والرفع'), ('execute', 'للتنفيذ'), ('file', 'للحفظ')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='correspondence.correspondence')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mail_referral', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'وارد خارجي'), ('OUT', 'صادر خارجي'), ('INT', 'مذكرة داخلية'), ('CIR', 'تعميم'), ('DEC', 'قرار إداري'), ('RPL', 'رد على وارد')], max_length=4)),
                ('year', models.PositiveSmallIntegerField()),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'year'), name='mail_sequence_year_kind')],
            },
        ),
        migrations.AddConstraint(
            model_name='correspondence',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'registered', 'referred', 'active', 'waiting', 'review', 'approval', 'signing', 'issued', 'sent', 'received', 'done', 'archived', 'returned', 'cancelled'])), name='mail_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='correspondence',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['IN', 'OUT', 'INT', 'CIR', 'DEC', 'RPL'])), name='mail_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='correspondence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reference__isnull', False), ('signed_at__isnull', False), ('status__in', ['issued', 'sent', 'received'])), models.Q(('status__in', ['issued', 'sent', 'received']), _negated=True), _connector='OR'), name='issued_mail_signed_numbered'),
        ),
    ]
