# Generated by Django 5.2.18 on 2026-10-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_immutable_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='approval_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
