# Generated by Django 5.2.18 on 2026-10-08 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_alter_correspondence_approval_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='search_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'بانتظار الاستخراج'), ('done', 'تم الاستخراج — يحتاج مراجعة'), ('failed', 'تعذر الاستخراج')], default='pending', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ocr_job', to='correspondence.mailattachment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('filters', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='mail_saved_search_name')],
            },
        ),
    ]
