# Generated by Django 5.2.18 on 2026-10-08 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_correspondence_search_text_ocrjob_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='batch',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='referral',
            name='mode',
            field=models.CharField(choices=[('parallel', 'متوازية'), ('sequential', 'متسلسلة')], default='parallel', max_length=12),
        ),
        migrations.AddField(
            model_name='referral',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
