# Generated by Django 5.2.18 on 2026-10-08 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_followup_integrity'),
        ('correspondence', '0005_referral_batch_referral_mode_referral_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='correspondence',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'IN'), models.Q(('status', 'cancelled'), _negated=True)), fields=('party', 'external_number'), name='mail_incoming_external_unique'),
        ),
    ]
