# Generated by Django 5.2.18 on 2026-10-08 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_followup_integrity'),
        ('correspondence', '0006_correspondence_mail_incoming_external_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('hr', 'hr'), ('email', 'email'), ('sms', 'sms'), ('dms', 'dms'), ('signature', 'signature'), ('webhook', 'webhook')], max_length=30)),
                ('endpoint', models.URLField()),
                ('secret_env', models.CharField(help_text='اسم متغير البيئة؛ لا تحفظ المفتاح هنا', max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('events', models.JSONField(default=list)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('status', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField()),
                ('download', models.BooleanField(default=False)),
                ('printing', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.correspondence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('dedup', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.integration')),
            ],
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('imposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.correspondence')),
            ],
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('last_step', models.BigIntegerField(default=-1)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('source', models.CharField(max_length=80)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('summary', models.JSONField(default=dict)),
                ('committed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('critical_sms', models.BooleanField(default=False)),
                ('daily_digest', models.BooleanField(default=True)),
                ('last_digest', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('legal_basis', models.TextField()),
                ('categories', models.JSONField(default=list)),
                ('recipients', models.TextField(blank=True)),
                ('retention_reference', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('action', models.CharField(choices=[('destroy', 'إتلاف المرفقات'), ('permanent', 'حفظ دائم')], max_length=20)),
                ('state', models.CharField(default='proposed', max_length=20)),
                ('reason', models.TextField()),
                ('minutes_reference', models.CharField(blank=True, max_length=250)),
                ('proof', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correspondence.correspondence')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=20)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('expires', models.DateTimeField()),
                ('signed_pdf', models.FileField(blank=True, upload_to='signed/%Y/%m/')),
                ('evidence', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_requests', to='correspondence.correspondence')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(choices=[('access', 'اطلاع'), ('correct', 'تصحيح'), ('destroy', 'إتلاف'), ('withdraw', 'سحب موافقة')], max_length=20)),
                ('description', models.TextField()),
                ('state', models.CharField(default='submitted', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('event_id', models.CharField(max_length=100)),
                ('digest', models.CharField(max_length=64)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'event_id'), name='hr_event_unique')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=100)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='hr_source_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='ExternalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=100)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='hr_unit_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='RetentionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='correspondence.retentioncase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'actor'), name='retention_approval_unique')],
            },
        ),
    ]
