# Generated by Django 5.2.18 on 2026-10-08 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0007_integration_apicalllog_exportgrant_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='first_referred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='personal_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='program_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='project_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='rich_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='brand_name',
            field=models.CharField(default='جمعية الإحسان للخدمات الاجتماعية', max_length=200),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='footer',
            field=models.TextField(default='جمعية الإحسان للخدمات الاجتماعية'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='license_number',
            field=models.CharField(default='1504', max_length=30),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='national_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='retention_committee',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='retention_quorum',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='signature_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='pdf_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='reserved_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
