# Generated by Django 5.2.18 on 2026-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0008_correspondence_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
