# Generated by Django 5.2.18 on 2026-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0009_alter_correspondence_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='page_confidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='proposals',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
