# Generated by Django 5.2.18 on 2026-10-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0010_ocrjob_page_confidence_ocrjob_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='integration',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
