# Generated by Django 5.2.18 on 2026-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0011_integration_options_alter_integration_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='paused_hours',
            field=models.FloatField(default=0),
        ),
    ]
