# Generated by Django 5.2.18 on 2026-10-08 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_followup_integrity'),
        ('correspondence', '0012_correspondence_paused_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='correspondence',
            name='mail_status_valid',
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('registered', 'مسجّل'), ('referred', 'محال'), ('active', 'قيد المعالجة'), ('suspended', 'معلّق بمبرر'), ('waiting', 'بانتظار رد جهة خارجية'), ('review', 'تدقيق'), ('approval', 'بانتظار اعتماد'), ('signing', 'بانتظار توقيع'), ('issued', 'مُصدَر برقم'), ('sent', 'مُرسَل'), ('received', 'مستلم'), ('done', 'منجز'), ('archived', 'مؤرشف'), ('returned', 'مُعاد للتصحيح'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='correspondence',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'registered', 'referred', 'active', 'suspended', 'waiting', 'review', 'approval', 'signing', 'issued', 'sent', 'received', 'done', 'archived', 'returned', 'cancelled'])), name='mail_status_valid'),
        ),
    ]
