[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=14
repo1-cipher-type=aes-256-cbc
start-fast=y
archive-async=y
spool-path=/var/spool/pgbackrest
log-level-console=warn
[ehsan]
pg1-path=/var/lib/postgresql/data
